_target_: models.seqrec_module.SeqRecLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net: # this is for the type of the of the model
  _target_: models.components.bert4rec.BERT4RecModel
  mask_ratio: 0.2 # specialize for bert4rec
  hidden_dropout_prob: 0.1
  item_size: 100 # this needs to be customized based on the data set.
  hidden_size: 64
  max_seq_length: 50
  initializer_range: 0.02
  transformer:
    hidden_size: 64 # need to be called again
    hidden_dropout_prob: 0.1 # this too
    num_attention_heads: 4
    num_hidden_layers: 2
    attention_probs_dropout_prob: 0.5
    hidden_act: gelu

# compile model for faster training with pytorch 2.0
compile: false
